### ISSUE TITLE
关于Q更新

### ISSUE THREAD

**Issue by Sobbbbbber** [watchernyu/REDQ#4]
您好：
       在更新Q网络是，计算所有Q网络的loss之和q_loss_all，然后q_loss_all.backward()。
       请问是否可以单独的计算每个网络的q_loss, 各自执行q_loss.backward,然后optimize呢？

**Comment by watchernyu** [comment]
你好谢谢你提出的issue！是的这两种情况都是没问题的，因为将几个loss加在一起和不加在一起分别求导求出来是一样的！(从数学的层面来说也是一样的) 所以无论是一起进行还是分别求都不影响。
Hope that helps!

**Comment by watchernyu** [comment]
If the problem is solved, then I will close the issue now, thanks!
