### ISSUE TITLE
Reproduce figures of the paper

### ISSUE THREAD

**Issue by MarWaltz** [watchernyu/REDQ#5]
Dear authors,

Thank you for providing this excellent paper and the complementary code-base.

However, I would like to reproduce the figures from the paper exactly, e.g., the ones in which the avg and the std of the normalized bias for the Ant-env is depicted. Is this code also publicly available or should I rather try to write this myself? Unfortunately, I could not find it in this repository.

Best,
Martin

**Comment by watchernyu** [comment]
Hi Martin! Thanks for posting the issue! You don't need to write it
yourself! I can upload all the plotting utilities and data we have so that
you can easily reproduce the figures! I will try get this done in the next
few days!

MarWaltz ***@***.***> 于 2021年7月22日周四 下午9:00写道：

**Comment by MarWaltz** [comment]
Great, thanks a lot!

**Comment by watchernyu** [comment]
@MarWaltz Hi! We have uploaded data and the code for reproducing the figures in the paper! We have also added the Q bias evaluation methods in the latest codebase, so now you can log these bias information while running experiments. Currently the plotting uses Seaborn 0.8.1 version (using the tsplot function. Note this function is deprecated in newer version of Seaborn. If you want to use newer version you can try modify the code slightly, shouldn't be too hard. If I have time this week I will also try update code to support newer version of Seaborn and write some more tutorial). The link to download the data and how to plot the figures are discussed on the README page. 
Hope that helps! If you encounter any issue please let us know!

**Comment by MarWaltz** [comment]
Dear Che Wang,

Thanks again for providing the details.

I came back to your approach of bias quantification, and I think I have kind of a misunderstanding. In the paper, Section 3, you define a Q-function Q^{\pi} for a policy \pi. Further, Q^{\phi} is an estimate of it, and the bias is consequently Q^{\phi} - Q^{\pi}. In the experiment, you consider the current behavior policy \pi induced by your current actor, which contains some noise for exploration (I looked it up in your code). This is the policy for generating your MC trajectories, which serve as the ground truth and are used to compute returns by definition. 

But is comparing these returns created by the continuous analog of an \epsilon-greedy strategy with the learned Q's of the critic a valid approach? In Q-Learning, or the critic training in this case, the Q directly approximates Q* (Sutton & Barto, 2018, p. 131), regardless of the behavior policy. So I am wondering how the pursued approach can be justified. 

Again, I believe that I have some conceptual misunderstanding, and I would be glad if you could help me with this point.

Best,
Martin
